# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                           #
#                                                           #
#                    AnotherTablistPlugin                   #
#                         by adiko01                        #
#                                                           #
#                    This Project is on:                    #
#      https://github.com/adiko01/AnotherTablistPlugin      #
#   https://dev.bukkit.org/projects/anothertablistplugin    #
#                                                           #
#                                                           #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Important Links
# Wiki:            https://github.com/adiko01/AnotherTablistPlugin/wiki
# Bugtracker:      https://github.com/adiko01/AnotherTablistPlugin/issues


header: "&aAnother&4Tablist&aPlugin\n &1Welcome to &aexample.com\n {weekday} {date} {time2}"
footer: "&6Check out our website  >> &aexample.com\n&6Online: {players} of {max-players} Players \n The motd: {motd}"


# Unter header kann der Text f端r 端ber der Tablist eingetragen werden
# Unter footer der Text f端r drunter
# Benutze die normalen Minecraft Farbcodes (https://minecraft.fandom.com/de/wiki/Formatierungscodes#Farbcodes)
# Benutze \n f端r einen Zeilenumbruch

# Under header the text for above the tablist can be entered
# Under footer the ext for below
# Use the normal Minecraft color codes (https://minecraft.fandom.com/wiki/Formatting_codes#Color_codes)
# Use \n for a line break

# Wildcard -- German -- English
# {players} -- Anzahl Spieler -- Count of online player
# {max-players} -- Maximale Anzahl der Spieler -- Count of maximal possible players
# {motd} -- Zeigt die MOTD -- Schows the MOTD
# {date} -- Aktuelles Datum -- Current date
# {weekday} -- Aktueller Wochentag -- Current day of the week
# {month} -- Aktueller Monat -- Current month
# {time} -- Aktuelle Uhrzeit (HH:MM) -- Current time (HH:MM)
# {time2} -- Aktuelle Uhrzeit (HH:MM:SS) -- Current time (HH:MM:SS)