# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                           #
#                                                           #
#                    AnotherTablistPlugin                   #
#                         by adiko01                        #
#                                                           #
#                    This Project is on:                    #
#      https://github.com/adiko01/AnotherTablistPlugin      #
#   https://dev.bukkit.org/projects/anothertablistplugin    #
#                                                           #
#                                                           #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Important Links
# Wiki:            https://github.com/adiko01/AnotherTablistPlugin/wiki
# Bugtracker:      https://github.com/adiko01/AnotherTablistPlugin/issues

header: "&4Another&6Tablist&4Plugin\n &aWelcome to &aexample.com\n &7{weekday} {date} {time2}"
footer: "&aOnline: {players} of {max-players} players\n The MOTD: &6{motd}"

# Typ des Zufualls
# Typ of Random
# s -> Sekunde (Echtzeit) -- second (realtime)
# m -> Minute (Echtzeit) -- minute (realtime)
# h -> Stunde (Echtzeit) -- hour (realtime)
# d -> Tag (Echtzeit) -- day (realtime)
# md -> Minecraft Tag (20 Minuten) -- minecraft day (20 minutes)

randomtype: md

# Ersetzt die Wildcard {random} oder {RANDOM} mit einem dieser Strings (Maximal nur 5 Strings)
# Replaces the Wildcard {random} or {RANDOM} with one of these strings (Maximal only 5 Strings)

random0: ""
random1: ""
random2: ""
random3: ""
random4: ""
random5: ""

# Unter header kann der Text für über der Tablist eingetragen werden
# Unter footer der Text für drunter
# Benutze die normalen Minecraft Farbcodes (https://minecraft.fandom.com/de/wiki/Formatierungscodes#Farbcodes)
# Benutze \n für einen Zeilenumbruch

# Under header the text for above the tablist can be entered
# Under footer the ext for below
# Use the normal Minecraft color codes (https://minecraft.fandom.com/wiki/Formatting_codes#Color_codes)
# Use \n for a line break

# Wildcard -- German -- English
# {players} -- Anzahl Spieler -- Count of online player
# {max-players} -- Maximale Anzahl der Spieler -- Count of maximal possible players
# {motd} -- Zeigt die MOTD -- Shows the MOTD
# {date} -- Aktuelles Datum -- Current date
# {weekday} -- Aktueller Wochentag -- Current day of the week
# {month} -- Aktueller Monat -- Current month
# {time} -- Aktuelle Uhrzeit (HH:MM) -- Current time (HH:MM)
# {time2} -- Aktuelle Uhrzeit (HH:MM:SS) -- Current time (HH:MM:SS)