name: AnotherTablistPlugin
version: '${project.version}'
main: de.adiko01.anothertablistplugin.AnotherTablistPlugin
api-version: 1.19
authors: [ adiko01 ]
website: https://github.com/adiko01
commands:
  atp:
    description: Commands for this Plugin.
permissions:
  atp.about:
    description: Allows /atp about and /atp bug
    default: op
  atp.bug:
    description: Allows /atp bug
    default: op
  atp.help:
    description: Allows /atp help
    default: op
  atp.reload:
    description: Allows /atp reload
    default: op