name: AnotherTablistPlugin
version: '${project.version}'
main: de.adiko01.anothertablistplugin.AnotherTablistPlugin
api-version: 1.19
authors: [ adiko01 ]
website: https://github.com/adiko01
commands:
  atp:
    description: Commands for this Plugin
    permission: AnotherTablistPlugin.about
    permission-message: You do not have /<permission>
permissions:
  AnotherTablistPlugin.about:
    description: Allows /atp about
    default: op